name: dio_http
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 5.0.3
homepage: https://github.com/dart-tools/dio_http

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_parser: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.11
  pedantic: ^1.10.0
